In [2]:
import numpy as np

grid = np.zeros((3,3))
reward = np.zeros((3,3))
reward[2,2] = 1

q = np.zeros((3,3,4))  # actions: up,down,left,right
alpha = 0.1
gamma = 0.9

for episode in range(50):
    x,y = 0,0
    while (x,y) != (2,2):
        action = np.random.randint(0,4)
        nx, ny = x, y

        if action == 0 and x>0: nx -= 1
        if action == 1 and x<2: nx += 1
        if action == 2 and y>0: ny -= 1
        if action == 3 and y<2: ny += 1

        q[x,y,action] += alpha * (reward[nx,ny] + gamma*np.max(q[nx,ny]) - q[x,y,action])
        x,y = nx,ny

print("Q-table:")
print(q)

Q-table:
[[[0.29287319 0.38918248 0.27368713 0.3055502 ]
  [0.17793515 0.35310111 0.22289256 0.42861328]
  [0.35040115 0.66301851 0.21222499 0.42341222]]

 [[0.21379987 0.53987522 0.35917244 0.51288917]
  [0.19372733 0.70220424 0.22036173 0.60258032]
  [0.21121604 0.91137062 0.37107396 0.54007338]]

 [[0.36897224 0.43895541 0.38999297 0.71899045]
  [0.28420612 0.59201833 0.39046125 0.94185026]
  [0.         0.         0.         0.        ]]]
